apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: netflix
  namespace: netflix
spec:
  version: 8.6.0
  count: 1
  elasticsearchRef:
    name: netflix
  http:
   service:
     spec:
       type: ClusterIP
  podTemplate:
    metadata:
      labels:
        app: elastic
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 600Mi
            cpu: 500m