kind: ConfigMap
apiVersion: v1
metadata:
  name: consumer-pipeline-config
  namespace: netflix
data:
  logstash.yml: | 
    pipeline:
      batch:
        size: 125
        delay: 50
  pipelines.yml: |
      input {
        kafka
             {
                  bootstrap_servers => "netflix-kafka-bootstrap:9092"
                  topics => "LOGSTASH"
           }
            }

        output {
          elasticsearch {
              hosts => "prime-es-http.prime.svc.cluster.local:9200"
              user => "elastic"
              password => "${ES_PASSWORD}"
              ssl => true
              ssl_certificate_verification => false
              ecs_compatibility => disabled
              index => logstash
          }
        }
  jvm.options: | 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prime-logstash
  namespace: prime
  labels:
    app:  logstash
spec:
  selector:
    matchLabels:
      app: logstash
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  logstash
    spec:
      containers:
      - name:  logstash
        image:  docker.elastic.co/logstash/logstash:8.6.0
        env:
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prime-es-elastic-user
                key: elastic
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 1.5Gi
        readinessProbe:
          failureThreshold: 3
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              curl --fail localhost:9600
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort:  9600
          name:  logstash
        volumeMounts:
        - name: consumer-pipeline-config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: consumer-pipeline-config
          mountPath: /usr/share/logstash/pipeline/pipelines.yml
          subPath: pipelines.yml
      volumes:
        - name: consumer-pipeline-config
          configMap:
            name: consumer-pipeline-config
      restartPolicy: Always