kind: ConfigMap
apiVersion: v1
metadata:
  name: producer-pipeline-config
  namespace: prime
data:
  logstash.yml: | 
    pipeline:
      batch:
        size: 125
        delay: 50
  pipelines.yml: |
      input {
      generator {
        lines => [
          "line 1",
          "line 2",
          "line 3"
        ]
        # Emit all lines 3 times.
        count => 3
      }
       } 

      output {
        kafka {
        
                  bootstrap_servers => "prime-kafka-bootstrap:9092"
                  topic_id => "LOGSTASH"
        }
        }

  jvm.options: | 

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name:  prime-producer-logstash
  namespace: prime
  labels:
    app:  logstash
spec:
  selector:
    matchLabels:
      app: logstash
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  logstash
    spec:
      containers:
      - name:  logstash
        image:  docker.elastic.co/logstash/logstash:8.6.0
        env:
          - name: ES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: prime-es-elastic-user
                key: elastic
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: 500m
            memory: 1.5Gi
        readinessProbe:
          failureThreshold: 3
          exec:
            command:
            - sh
            - -c
            - |
              #!/usr/bin/env bash -e
              curl --fail localhost:9600
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        ports:
        - containerPort:  9600
          name:  logstash
        volumeMounts:
        - name: producer-pipeline-config
          mountPath: /usr/share/logstash/config/logstash.yml
          subPath: logstash.yml
        - name: producer-pipeline-config
          mountPath: /usr/share/logstash/pipeline/pipelines.yml
          subPath: pipelines.yml
      volumes:
        - name: producer-pipeline-config
          configMap:
            name: producer-pipeline-config
      restartPolicy: Always